"""rename department

Revision ID: 90c0f0f62b5a
Revises: a6d2d8283686
Create Date: 2025-03-27 08:22:55.876830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c0f0f62b5a'
down_revision = 'a6d2d8283686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###